import "../globals.css";
import Navbar from "../Navbar";
import Menu from "./Menu";
import Footer from "../Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar">
      <body>
        <Navbar />
        {children}
        <Menu />
        <Footer />
      </body>
    </html>
  );
}
