"use client"
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'
import { ToastContainer } from 'react-toastify'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar">
      <body className='h-screen' >
            {children}
      </body>
      <ToastContainer position='bottom-right' autoClose={2000} rtl={true}/>
    </html>
  );
}
