'use client';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import { SessionProvider } from 'next-auth/react';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="ar">
      <SessionProvider session={session}>
        <body className="h-screen">{children}</body>
        <ToastContainer position="bottom-right" autoClose={2000} rtl={true} />
      </SessionProvider>
    </html>
  );
}
